---
# yamllint disable rule:comments rule:line-length
name: Release
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
permissions: {}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true # zizmor: ignore[artipacked]
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "zulu"
          java-version: "21"
          server-id: central
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
      - name: Install xpath
        run: sudo apt install -y libxml-xpath-perl
      - name: Prepare and perform release
        run: |
          git config --global committer.email "48418865+dropwizard-committers@users.noreply.github.com"
          git config --global committer.name "Release Action"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"
          VERSION=$(xpath -q -e '/project/properties/flywayVersion/text()' pom.xml)
          ./mvnw -B -V -ntp -DreleaseVersion="${VERSION}" release:prepare release:perform
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
          SIGN_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GH_TOKEN: ${{ github.token }}
